# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daylog < Formula
  desc "Write your daily standup throughout the day"
  homepage "https://github.com/keyneston/daylog"
  version "0.0.1"
  license "BSD-3-Clause"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/keyneston/daylog/releases/download/v0.0.1/daylog_0.0.1_darwin_amd64.tar.gz"
    sha256 "b35717665d5dbd161dfc7f7bc117f5851dc68271c949b87af149d986e1ca67e8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/keyneston/daylog/releases/download/v0.0.1/daylog_0.0.1_darwin_arm64.tar.gz"
    sha256 "6140bae4501674c44d048cbe232da82998e8d3d332af9dabd9de415a697b8e67"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/keyneston/daylog/releases/download/v0.0.1/daylog_0.0.1_linux_amd64.tar.gz"
    sha256 "adaccdd982019839d4cd15652ab4dde712d897907550e7e00bd24583ff92456b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/keyneston/daylog/releases/download/v0.0.1/daylog_0.0.1_linux_arm64.tar.gz"
    sha256 "3851bf0137a83f95b35548f1fde4c63e3043997b800ff3eaf62f5772f862c341"
  end

  def install
    bin.install "daylog"
  end

  test do
    system "#{bin}/daylog --h"
  end
end
