# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mktable < Formula
  desc "Make markdown tables from the command line"
  homepage "https://github.com/keyneston/mktable"
  version "0.0.4"
  license "BSD-3-Clause"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/keyneston/mktable/releases/download/v0.0.4/mktable_0.0.4_darwin_amd64.tar.gz"
    sha256 "556dd4780991e8b62f18fbc6f1bcd3844bf53c579f0f2da3bd074226c8b2353d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/keyneston/mktable/releases/download/v0.0.4/mktable_0.0.4_darwin_arm64.tar.gz"
    sha256 "7a82e0e2d7437fcf4136c55867ac2fa7d1fb21dbd2515c39b815bdf208825594"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/keyneston/mktable/releases/download/v0.0.4/mktable_0.0.4_linux_amd64.tar.gz"
    sha256 "2fbeafbccbe96aeca1b41888d8e57959058bab9df68f3a53a444c1ca124e64c1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/keyneston/mktable/releases/download/v0.0.4/mktable_0.0.4_linux_arm64.tar.gz"
    sha256 "1aa3a14d1028011c0649e36969f00bc107c406678a609f10acb7af6a965650d3"
  end

  def install
    bin.install "mktable"
  end

  test do
    system "#{bin}/mktable --h"
  end
end
